### PR TITLE
Stale message improvement

### PR DESCRIPTION
**Pull request by awolfe76**
Finishes up #102 by improving stale message and adding an action to login.

Had to include the `error` template.

## Screenshot

stale-message

### CODE REVIEW

**Comment by keileyo** [comment]
cool!

**Comment by awolfe76** [comment]
@hkeeler - I had thought about that too. I think it's ok, at least for now. It's good to give the person some sort of action to take. We could reword it all a bit to just say "Go to the home page" and the button to just say "Home" ... or something else entirely.

Any thoughts @keileyo @designlanguage?

**Comment by wpears** [comment]
Also, it looks like the text that landed has diverged from what was in the issue. I think the "expired" language is more accurate, since this primarily happens if a user doesn't click their link in the timeout window.

**Comment by awolfe76** [comment]
@wpears - I agree. Updated in e9adb41 and we should be ok here.

**Pull request merged**
